const doctors = [
    {
        name:"Yassin Abdel-Warith",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/6b434603-0bcf-4db3-a514-39ae09e6eb11/fx1.jpg",
        short:"His death from COVID-19 robbed Yemen not only of a leader in the response, but also of someone with an unparalleled epidemiological understanding of the country. “From the first day he returned to Yemen after he got his medical degree until the last day he died, he dedicated his life for the health of the Yemeni”, said Adel Al-Jasari, the Malaria and Vector Control Officer for the WHO Country Office in Yemen",
        long:"Abdel-Warith received a degree in medicine and surgery from a Soviet Union university in 1974 and a master's degree in public health and epidemiology from the University of Tehran in Iran in 1978. On his return to Yemen, he was one of the only doctors with a specialisation in public health in the country, Al-Jasari said. After working briefly as the head of a rural health unit in his home region, Taiz, Abdel-Warith joined the Ministry of Health in the capital, Sana'a, where he spent decades working in various roles. “He was really a reference person for all of us”, said Al-Jasari, who worked as the head of the Ministry of Health's malaria control programme in 2004. Although Abdel-Warith was assigned to work as a monitoring and evaluation officer on HIV at the time, “when we called him or asked him to join our team or to support us, he never said no”, said Al-JasariHe also never looked for personal advancement, Al-Jasari said, instead nominating colleagues to speak to the media or to brief superiors on successes. He preferred to stay in the background, coordinating between the ministry and other agencies and quietly lobbying for his preferred strategies. His experience was considered so invaluable that even after he retired from the Ministry of Health in 2010, WHO Yemen regularly recruited him to help coordinate activities following a disease outbreak, including a key role coordinating efforts to respond to a cholera outbreak that began in 2016. “He gave to the people and the country as much as he could”, Al-Jasari said."
    },{
        name:"Arpik Asratyan",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/d7dfdf69-7c5b-47b9-bcd4-c9a8b64b9615/fx2.jpg",
        short:"Epidemiologist who specialised in viral hepatitis. She was born on June 25, 1950, in Armenia, and died on March 27, 2020, in Moscow, Russia, aged 69 years.",
        long:"Arpik Asratyan joined the Department of Epidemiology and Modern Vaccination Technologies at what is now I M Sechenov First Moscow State Medical University at a crucial moment in 1997. An expert in viral hepatitis, her arrival coincided with “a period at the turn of the century when the problem of parenteral viral hepatitis was especially urgent both in Russia and in the world”, said her colleague Elena Gennadievna Simonova, a Professor in the Department of Epidemiology and Modern Vaccination Technologies. “Professor Asratyan was an extremely popular scientist and teacher who extensively trained scientific personnel. She was instrumental in the prevention of viral hepatitis”, said Simonova.Asratyan developed her interest in epidemiology and infectious diseases during her final years at Yerevan State Medical University in Yerevan, Armenia, according to her son, Airazat Kazaryan, a Professor of Surgery in the Department of Gastrointestinal Surgery at Østfold Hospital Trust in Gralum, Norway. When a PhD fellowship position was announced in 1973 at what is now the Gamaleya Research Institute of Epidemiology and Microbiology in Moscow, “she applied to it without doubts”, he said. She would remain there for much of her career. Asratyan pursued a doctorate in medical sciences from the Department of Epidemiology of the Russian Medical Academy of Postgraduate Education in 1977 and earned her professorship at the First Moscow State Medical University following her 1997 defence of her habilitation thesis. In addition to viral hepatitis, she taught classes on HIV and other sexually transmitted infections, as well as nosocomial infections. Asratyan's research paid “special attention to the study of modern trends in the dynamics of the epidemic processes of [hepatitis] infections”, Simonova said. “In particular, she and her students conducted research aimed at studying combined infectious pathology”, including co-infections with hepatitis B or C virus and with tuberculosis, HIV, or sexually transmitted diseases. She also worked with colleagues to oversee epidemiological education and supervision in some of Russia's specialised infection hospitals. “Professor Asratyan was the soul of any company and team, always positive, with a smile on her beautiful face”, Simonova said. Asratyan's husband, Mishik Kazaryan, a specialist in laser physics and optics, also died of COVID-19. In addition to their son, Airazat, they are survived by a daughter, Serine.",

    },
    {
        name:"Sara Bravo Lopez",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/57f59f39-f1f2-40b4-97cd-760bf5f6c884/fx3.jpg",
        short:"Primary care physician. She was born on June 20, 1991, in Ciudad Real, Spain, and died on March 29, 2020, in Alcazar de San Juan, Spain, aged 28 years.",
        long:"There is a tradition at the Faculty of Medicine at the University of Valladolid in Spain that when medical students reach the end of their studies they celebrate a last dinner with their professors. Although she had a leg injury as her class's event approached in 2015, Sara Bravo Lopez was determined to take part in the celebration. “She kept dancing all night, happy, because we were finally doctors”, said her classmate Luis Cabezudo Molleda, an internal medicine resident at the Complejo Asistencial Universitario de Palencia.After graduation, Bravo quickly found a position as a primary care doctor at the Centro de Salud de Mota del Cuervo in the province of Cuenca, Spain, and was working there when she became ill with COVID-19. It was part of her job to assess patients that came into the facility. Cheerful and indefatigable, she had a gift for soothing patients. Cabezudo said Bravo possessed that ability even in her medical school days, where she had a knack for calming her classmates before important exams. “She had the exact words that help people relax”, he said. Bravo had taken a colleague's shift and was caring for patients who came into the health centre and were later diagnosed with COVID-19, Cabezudo said. “She died because she loved her work, she did it bravely and she did it always thinking of others”, he said.One of her professors, Ignacio Rosell, an Associate Professor in the Department of Preventive Medicine and Public Health at the University of Valladolid, said Bravo's fellow students and teachers “remember her as a beautiful person”, at the outset of a promising career, “always ready to collaborate and to help out”. Bravo is survived by her mother, Teresa, and her brother.",
        
    },
    {
        name:"Claudia Nogueira Cardoso",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/1af4cf9e-dac9-49ad-8851-4211d2ccd869/fx4.jpg",
        short:"Endocrinologist. She was born on Oct 12, 1963, in Rio de Janeiro, Brazil, and died on April 8, 2020, in Rio de Janeiro, aged 56 years.",
        long:"Claudia Nogueira Cardoso always made sure to keep extra medical supplies in her car or her bag. As she travelled around Rio de Janeiro, Brazil, where she lived, she offered help to people in the community. “She was very charitable, a friend and companion who always had a friendly word”, her brother Claumyr Cardoso said. “She must be remembered as a person who liked to help everyone.Cardoso decided to be a doctor at a young age, her brother remembered, inspired by her own paediatrician. She earned her medical degree at the Souza Marques School of Medicine in Rio de Janeiro before specialising in endocrinology at Santa Casa da Misericórdia, a local hospital. She became interested in the field partly because she had diabetes. After completing her studies, she opened a private practice in Rio de Janeiro, while also working in other clinics around the city. Claumyr Cardoso, who is a dental surgeon, said she was devoted to her patients and agreed to continue providing treatment even as COVID-19 reached the city. In addition to her brother, Cardoso is survived by her husband, João, her parents, and a son, Rodrigo, who is also a physician.",
        
    },
    {
        name:"Livia Carrion",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/9d1914b7-e26a-4fff-a8cc-9dfe6ede662e/fx5.jpg",
        short:"Former Director of Epidemiology of the Institute of Public Health, Bolivar state, Venezuela. She was born on Sept 9, 1953, in Puerto de Hierro, Venezuela, and died on July 25, 2020, in Ciudad Bolivar, Venezuela, aged 66 years.",
        long:'Livia Carrion studied medicine at the Universidad de Oriente in Ciudad Bolivar, Venezuela, a school with the motto, “From the town we come and to the town we go”. She would go on to dedicate her career to providing medical services to neglected communities, often in far-flung locations. “Her sublime love and dedication to medicine and to helping the needy encouraged her to study and to work for 35 years in public health, never practising private medicine”, said her daughter Katherine Sulbaran.After receiving her medical degree in 1981, Carrion began her career in Maripa, a remote town in the centre of Venezuela, providing care to the town\'s residents and nearby rural communities. Her career took her back to Ciudad Bolivar, the capital of Bolivar state, but her colleagues said she remained committed to the rural communities where she spent her early years as a doctor. After she was named Director of Epidemiology of the state\'s Institute of Public Health in 1994, she mounted a malaria care and treatment campaign among the state\'s remote, Indigenous populations that served as an example of how this service should work”, said Frank Morillo, the subdirector of the epidemiology department at Ruiz y Páez University Hospital Complex in Ciudad Bolivar. She joined Morillo at Ruiz y Páez, taking over the epidemiology department in 2002. The hospital was often a centre for regional epidemic responses, including an outbreak of influenza A H1N1 that began in 2009. Together we faced the management of the H1N1 pandemic in our hospital and we handled the situation successfully. She was tireless”, Morillo said. “She always had a smile and a very good attitude”, said Oriana Urbaez, a nurse at Ruiz y Páez University Hospital Complex. “She was an example of the constant and tireless fighter against every health problem, every disease, every epidemic, every outbreak.”Although Carrion was scheduled to retire 7 years ago, she continued working in the epidemiology department because of a shortage of doctors in the state. She was at the front line of the hospital\'s COVID-19 response, conducting tests and organising patient admissions. She is survived by her husband, Miguel Sulbaran, and three daughters, Katherine, Nathaly, and Reyna.',
        
    },
    {
        name:"Nino Antonio Cassanello Layana",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/5c5a2c65-924f-473e-8503-ed8a442160fa/fx6.jpg",
        short:"Internal medicine specialist. He was born on Jan 12, 1945, in Guayaquil, Ecuador, and died there on March 26, 2020, aged 75 years.",
        long:"Nino Cassanello Layana taught his medical students what he called the “principle of responsibility”. He believed that students needed to get to know their patients on a personal level and he encouraged them to ask about “not just the medical problems, but what kind of job he does, where he lived, what about his family”, said Cristobal Sanchez Metz, an adult hospitalist specialising in internal medicine in Washington, USA, who studied under Cassanello for 3 years. Cassanello taught at three different medical schools in Guayaquil, Ecuador—the University of Guayaquil, Universidad Catolica de Santiago de Guayaquil, and Universidad de Especialidades Espiritu Santo—and instructed thousands of students over his career, focusing primarily on internal medicine and medical semiology. “Teaching was in his blood and he knew how to transmit knowledge to countless generations of doctors who passed through his classrooms”, said Tomas Alarcon Aviles, a former student, who is now the head of neurology at Hospital Luis Vernaza in Guayaquil. Cassanello was even willing to help teach those who were not enrolled in his programmes. And they regularly sought him out, according to his son, Jerónimo Cassanello, a physician in the intensive care unit of Hospital Luis Vernaza, where his father also worked: “He was a very patient and motivating teacher and a captivating conversationalist.Nino Cassanello studied medicine at the University of Guayaquil's Faculty of Medicine, one of the universities where he would later teach. He started working at Hospital Luis Vernaza in 1971 and would remain there for more than 40 years, eventually rising to Director of the Internal Medicine Department. His expertise on medical semiology led him to write a textbook on medical history, physical examination, and differential diagnosis. “He was a very observant physician and he trained us to be observant in simple things”, Metz said. Cassanello is survived by his wife, seven children, and six grandchildren."
    }
    ,{
        name:"Adil El Tayar",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/f6a404c2-f8b8-429e-9193-def4e3e5306c/fx7.jpg",
        short:"Surgeon and organ transplant specialist. He was born on March 10, 1956, in Atbara, Sudan, and died on March 25, 2020, in London, UK, aged 64 years.",
        long:"As a young doctor working in Sudan, Adil El Tayar became aware of the rising problem of kidney diseases, particularly among young people. Without access to transplant surgery, patients were dependent on regular dialysis, which disrupted their ability to work or study. His mission was to replace the country's largely privatised, fragmented transplant services with a centralised registry and practice. “He wanted to build this service that could breed excellence, whether in diagnostics or on the operative or medical sides”, said his cousin, Hisham El-Khidir, a surgeon working at the Norfolk and Norwich University Hospital in the UK.Although he settled in the UK in the early 1990s, El Tayar would return to Sudan several times a year to build connections with doctors and officials who might be able to help him establish an improved transplantation service. He completed a master's degree in health service and management at the University of London to prepare himself for the task. In 2011, he returned to Sudan where he worked at Ibn Sina Hospital in Khartoum, while seeking to set up an organ transplant programme. He was able to get a centre started, but struggled amid the country's political uncertainty and the challenges of “a mainly privatised lucrative business where people didn't want to see a change to the service structure”, El-Khidir said. But El Tayar recognised “there was still room to help people on an individual basis”, El-Khidir said, and he would continue to provide medical advice and financial support to patients in Sudan for the rest of his life. “After his death, the family was overwhelmed with condolences from people, explaining how he had helped their families. No one knew this, not even his wife”, El-Khidir said.El Tayar was motivated to pursue medicine during his childhood when his brother died after his family was unable to find him the necessary care. After completing his medical studies at the University of Khartoum and working briefly in Sudan and Saudi Arabia, he moved to the UK in 1996. He studied at the University of West London and then worked at the West London Transplant Unit before moving to St George's Hospital. He would return there as a locum surgeon specialising in kidney transplantation after moving back to the UK from Sudan in 2015.“He was always up to help colleagues and patients, always willing to go the extra mile”, said Abbas Ghazanfar, a consultant transplant surgeon and clinical lead for renal and transplant services at St George's University Hospitals NHS Foundation Trust. “That's why he actually volunteered to go work during the COVID-19 pandemic.” El Tayar was working at Hereford County Hospital in the Midlands as a locum surgeon when he became ill. He is survived by his wife, Ekhlas, two daughters, Abeer and Ula, and two sons, Osman and Rahama."
    }
    ,
    {
        name:"Salvacion “Sally” Rodriguez Gatchalian",
        image:"https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/e359b407-737f-4734-9461-8a42bc97279b/fx8.jpg",
        short:"President of the Philippine Pediatric Society and former Assistant Director of the Research Institute for Tropical Medicine at the Philippine Department of Health. Born on Dec 4, 1952, in Manila, Philippines, she died on March 26, 2020, in Manila, aged 67 years.",
        long:"Salvacion Rodriguez Gatchalian, better known as Sally, knew how to disarm people. It was a skill that served her well as a paediatrician, but was even more crucial in the leadership roles she took on, including serving as President of the Pediatric Infectious Disease Society of the Philippines from 2014 to 2016 and of the Philippine Pediatric Society, beginning in 2018. “She was whip smart and a really great consensus builder”, said Edsel Salvana, the Director of the Institute of Molecular Biology and Biotechnology at the National Institutes of Health at the University of the Philippines (UP) Manila. “She was a great listener, but she was never afraid to speak up on controversial issues, even if it wasn't very popular.”Salvana grew close to Gatchalian during the controversy over the use of the dengue vaccine, Dengvaxia, that erupted in 2017 in the Philippines. Gatchalian, a long-time immunisation advocate and the cofounder of the Philippine Foundation for Vaccination, was among the experts trying to rally support for vaccination, while warning that misinformation about vaccines could lead parents to avoid immunising their children altogether. “We worked together to restore vaccine confidence”, Salvana said. Even as Gatchalian squared off against former associates during the Dengvaxia debate, she was able to rebuild those relationships in its aftermath, said Lulu Bravo, a close friend and Professor Emeritus of Pediatric Infectious and Tropical Diseases at UP Manila. “She was still friendly with everyone. Although she could disagree with you, I don't think she had any enemies.”"
    }

]